//OP CONTROL CONSTANTS
int LIFT_HIGH_SPEED = 127;
int LIFT_LOW_SPEED = 64;
int CLAW_OPEN_SPEED = 128;
int CLAW_CLOSE_SPEED = -70;

//LIFT CONTROL CONSTANTS
int LIFT_UP_SPEED = 128;
int LIFT_DOWN_SPEED = -60;
int LIFT_POTENTIOMETER_VALUE_HIGH= 1853;//from 2033 actual
int LIFT_POTENTIOMETER_VALUE_LOW = 462;//from 312 actual
int LIFT_DOWN_HOLDING_SPEED = 0;
int LIFT_UP_HOLDING_SPEED = 50;

//AUTONOMOUS CONTROL CONSTANTS

